### PR TITLE
Added `preset_questions` array field to the project model

### LINKED ISSUE #263: Add configurable preset questions to a project
Project model should have a array field that stores an array of upto 6 strings. These will be shown as below and should be configurable through the api endpoints.

image

### PR DESCRIPTION
**Pull request by GokulramGHV**
fixes #263

### CODE REVIEW

**Comment by bodhish** [comment]
Can we store more question options? It would have been nice if the UI showed different questions.

**Comment by skks1212** [comment]
@bodhish how many do we want?

**Comment by bodhish** [comment]
Let the backend store many; on FE show 4

**Comment by GokulramGHV** [comment]
@bodhish so shall I set the size to like 100 and randomly pick four out of the preset_questions and display it on the frontend?

**Comment by bodhish** [comment]
Yes; load random 4

**Comment by skks1212** [comment]
@GokulramGHV status on this?

**Comment by GokulramGHV** [comment]
@skks1212 Sorry for the delay, I've increased the no. of preset_questions and I've also made a frontend PR. Please review it and let me know if there's any changes.

**Review by skks1212 — APPROVED** [review]

**Pull request merged**
