### PR TITLE
self hosted model added

### PR DESCRIPTION
**Pull request by ishanExtreme**

### CODE REVIEW

**Comment by Ashesh3** [comment]
Is the endpoint supposed to be open? No authentication needed?

**Comment by ishanExtreme** [comment]
> Is the endpoint supposed to be open? No authentication needed?

for now, care-whisper endpoint is open we can deploy it in Private Network so that only care microservices can use it, or if required we can add auth. Currently its not for public usage so we don't necessary required auth we can just deploy it in a Private Network.

**Comment by Ashesh3** [comment]
> > Is the endpoint supposed to be open? No authentication needed?
> 
> for now, care-whisper endpoint is open we can deploy it in Private Network so that only care microservices can use it, or if required we can add auth. Currently its not for public usage so we don't necessary required auth we can just deploy it in a Private Network.

The URL you added, `whisper.ohc.network` is not within a private network and is accessible and usable publicly. I am able to post URL of an audio and get it to transcribe. Just wanted to make sure if this was intentional and that by pushing that URL in this commit, the endpoint now being publicly known is okay.

**Comment by ishanExtreme** [comment]
> > > Is the endpoint supposed to be open? No authentication needed?
> > 
> > 
> > for now, care-whisper endpoint is open we can deploy it in Private Network so that only care microservices can use it, or if required we can add auth. Currently its not for public usage so we don't necessary required auth we can just deploy it in a Private Network.
> 
> The URL you added, `whisper.ohc.network` is not within a private network and is accessible and usable publicly. I am able to post URL of an audio and get it to transcribe. Just wanted to make sure if this was intentional and that by pushing that URL in this commit, the endpoint now being publicly known is okay.

Oh okay gotchya, fixing the issue...

**Comment by ishanExtreme** [comment]
Fixed @Ashesh3

**Pull request merged**
