### PR TITLE
feat: Adds test

### PR DESCRIPTION
**Pull request by cp-Coder**
# Feature Request

## Proposed Changes

- [x] Adds tests
- [x] Adds `Github Workflow` to run test

### CODE REVIEW

**Comment by skks1212** [comment]
@cp-Coder Why have so many files been deleted?

**Comment by cp-Coder** [comment]
@skks1212 I have deleted the files because they don't contain useful code. The code in those files were not used anywhere that's why I cleaned up the codebase.

**Comment by skks1212** [comment]
@cp-Coder those are util files, they might come in handy down the line. For now, let it be the way it was

**Comment by cp-Coder** [comment]
Okay. I will undo the deletions.

**Comment by cp-Coder** [comment]
Will open a new PR

**Pull request closed without merging**
